#!/bin/bash

curl -L  http://mirrors.aliyun.com/repo/Centos-7.repo -o /etc/yum.repos.d/Centos-Base.repo

yum install -y epel-release
yum install -y net-tools wget tcpdump traceroute bzip2 zip unzip man-pages
yum install -y gdb gcc gcc-c++ make dstat strace ltrace lsof perf valgrind
yum install -y libpcap libpcap-devel ncurses ncurses-devel flex texinfo help2man readline-devel
yum install -y golang
yum install -y openssl-devel pcre-devel
yum -y install zlib-devel bzip2-devel sqlite-devel tk-devel libffi-devel

# download and install cgdb
wget https://cgdb.me/files/cgdb-0.6.8.tar.gz
tar xzf cgdb-0.6.8.tar.gz
cd cgdb-0.6.8
./configure --prefix=/usr/local
make && make install
cd -
rm -rf cgdb*

# download and install flamegraph
git clone https://github.com/brendangregg/FlameGraph.git  /usr/local/flamegraph
mv flameperf.sh /usr/local/bin/

# download and install nload
wget http://www.roland-riegel.de/nload/nload-0.7.4.tar.gz
tar zxf nload-0.7.4.tar.gz
cd nload-0.7.4
./configure
make && make install
cd -
rm -rf nload*

# download and install iftop
wget http://www.ex-parrot.com/pdw/iftop/download/iftop-1.0pre4.tar.gz
tar xzf iftop-1.0pre4.tar.gz
cd iftop-1.0pre4
./configure && make && make install
cd -

rm -rf iftop*

# install python3 instead of python2
wget https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
tar xzf Python-3.7.1.tgz
cd Python-3.7.1
./configure prefix=/usr/local/python3 && make && make install
rm -f /usr/bin/python
ln -s /usr/local/python3/bin/python3 /usr/bin/python
ln -s /usr/local/python3/bin/pip3  /usr/bin/pip
sed -i "s/^#\!.*/#\!\/usr\/bin\/python2/g" /usr/bin/yum
sed -i "s/^#\!.*/#\!\/usr\/bin\/python2/g" /usr/libexec/urlgrabber-ext-down
cd -

rm -rf Python*

rm -f docker_centos_dev
