#!/bin/bash

InstallPath=/usr/local/janus
Version=v0.4.3

yum install -y libmicrohttpd-devel jansson-devel libnice-devel openssl-devel \
    glib-devel opus-devel libogg-devel libcurl-devel libwebsockets-devel \
    pkgconfig gengetopt libtool autoconf automake

# yum install libsrtp, release is 1.4, cannot use
if [ ! -d libsrtp-2.2.0 ];then
    wget https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz
    tar xfv v2.2.0.tar.gz
    cd libsrtp-2.2.0
    ./configure --prefix=/usr --enable-openssl
    make shared_library && sudo make install
    cd -
fi

echo /usr/lib > /etc/ld.so.conf.d/janus.conf
ldconfig
ln -s /usr/lib/pkgconfig/libsrtp.pc /usr/lib64/pkgconfig/libsrtp.pc

git clone https://github.com/meetecho/janus-gateway.git
git checkout $Version
cd janus-gateway

sh autogen.sh

./configure --prefix=$InstallPath
make
make install
make configs

if [ ! -d $InstallPath/certs ];then
    mkdir -p $InstallPath/certs
    openssl req \
        -new \
        -newkey rsa:4096 \
        -days 365 \
        -nodes \
        -x509 \
        -subj "/C=AU/ST=NSW/L=Sydney/O=JanusDemo/CN=rtc.test.com" \
        -keyout $InstallPath/certs/mycert.key \
        -out $InstallPath/certs/mycert.pem
fi
