#! /bin/bash

if [ $# -lt 2 ];then
    echo $0 dirpath [options] PATTERN
    echo "  options and PATTERN are same with grep" 
    exit 1
fi

dirpath=$1
i=1
while [ $i -le $# ]
do
    pattern=$pattern" "$2
    ((i++))
    shift
done
resettem=$(tput sgr0)
files=`find ${dirpath} -type f 2>/dev/null`
if [ $? -ne 0 ];then
    echo ${dirpath} is not a directory
    exit 2
fi

for file in ${files}
do
    tmp=`grep ${pattern} ${file}`
    if [ -n "${tmp}" ];then
        echo ""
        echo -e '\E[34m'${file}:$resettem
        grep ${pattern} ${file}
    fi
done

